Create table census
( census_ID char(5) Not null,
age		varchar(3),
workClass	varchar(20),
fnlwgt 		numeric(7,0),
education	varchar(15),
education_num 	varchar(2),
marital_status 	varchar(25),
occupation 	varchar(30),
relationship 	varchar(20),
race 		varchar(25),
sex 		varchar(6),
capital_gain 	numeric(5),
capital_loss	numeric(5),
hours_per_week 	numeric(3),
income 		varchar(5),
country		varchar(30),
primary key (census_ID));

Create table happiness
(  Report_ID		char(5) Not Null,
census_ID			char(5),
country				varchar(30),
ladder_score		numeric(5,3),
GDP					numeric(5,3),
Social_support 		numeric(5,3),
life_expectancy		numeric(5,3),
Freedom_of_choice 	numeric(5,3),
Generosity 			numeric(5,3),
Perceived_corruption	numeric(5,3),
Ladder_score_Dystopia	numeric(5,3),
Explained_by_GDP		numeric(5,3),
Explained_by_social_support	numeric(5,3),
Explained_by_life_expectancy numeric(5,3),
Explained_by_Freedom_of_choice numeric(5,3),
Explained_by_generosity numeric(5,3),
Explained_by_Perceived_corruption numeric(5,3),
DystopiaPlusResidual	numeric(5,3),
Primary key (Report_ID),
FOREIGN KEY (census_ID) references happiness);